apiVersion: v1
kind: Service
metadata:
  name: aviation-weather # Service name
  namespace: aviation-weather # Namespace
spec:
  type: ClusterIP # Expose this service internally. LoadBalancer = External
  selector:
    app: aviation-weather
  ports:
  - port: 80 # External port
    targetPort: 8080 # Port inside the Pod, so request to <LoadBalancer-IP>:80 â†’ Pod:8080